'use strict'
module.exports = {
  NODE_ENV: '"production"',
  FIREBASE_API_KEY: '"APIKEY"',
  FIREBASE_AUTH_DOMAIN: '"YOURID.firebaseapp.com"',
  FIREBASE_DATABASE_URL: '"YOURURL"',
  FIREBASE_PROJECT_ID: '"YOURID"',
  FIREBASE_STORAGE_BUCKET: '""',
  FIREBASE_MESSAGING_SENDER_ID: '"YOURSENDERID"',
  FIREBASE_APP_ID: '"YOURAPPID"',
}
